"""Shared column conventions for all domain models.

Centralised so every table agrees on primary keys, timestamps and enum binding.
Divergence between tables is how schema drift starts.
"""

import uuid
from datetime import datetime

import sqlalchemy as sa
from sqlalchemy.orm import Mapped, mapped_column

from app.models.enums import ENUM_TYPE_NAMES, _StrEnum


def pg_enum(py_enum: type[_StrEnum]) -> sa.Enum:
    """Bind a Python enum to its native PostgreSQL type.

    `values_callable` makes SQLAlchemy persist the member *values* rather than
    the member *names*. They happen to be identical here, but relying on that
    coincidence would break silently the first time someone writes
    `ACTIVE = "active"`.

    `create_type=False` keeps type creation in the migration where it belongs;
    otherwise SQLAlchemy emits CREATE TYPE at table-create time and the
    migration loses control of ordering.
    """
    return sa.Enum(
        py_enum,
        name=ENUM_TYPE_NAMES[py_enum],
        values_callable=lambda e: [m.value for m in e],
        native_enum=True,
        create_type=False,
    )


def uuid_pk() -> Mapped[uuid.UUID]:
    """UUID primary key generated by the database.

    Server-side default rather than Python-side so raw SQL inserts - seed
    scripts, psql sessions, future migrations - get a valid id too.
    PostgreSQL 17 provides gen_random_uuid() natively; no extension needed.
    """
    return mapped_column(
        sa.Uuid(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
    )


class TimestampMixin:
    """created_at / updated_at, both maintained by the database.

    `updated_at` is driven by a trigger (see migration 0002), not by
    SQLAlchemy's `onupdate`. An ORM-side default would silently fail to fire for
    bulk updates, raw SQL and migrations - which is exactly when a stale
    timestamp is most misleading.
    """

    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    )


class SoftDeleteMixin:
    """Master data referenced by historical records is never hard-deleted.

    Deleting a driver who appears on last month's trips would either destroy
    that history or orphan it. Partial indexes filter on `deleted_at IS NULL`.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True), nullable=True
    )


# Money is NUMERIC everywhere. Float is never acceptable for currency, and
# NUMERIC(12,2) holds up to 9,999,999,999.99 - ample for INR trip values.
MONEY = sa.Numeric(12, 2)
# Kilograms, two decimal places.
WEIGHT_KG = sa.Numeric(10, 2)
