/**
 * Parity: the TypeScript port must agree with app/domain/route_progress.py.
 *
 * Fixtures are generated by RUNNING the Python implementation
 * (backend/scripts/route_progress_fixtures.py), not written by hand. A
 * hand-written expectation would only prove the porter and the tester made the
 * same mistake.
 *
 * TOLERANCE, described accurately. The comparison divides by
 * `max(1, abs(expected))`, so it is an ABSOLUTE tolerance of 1e-9 for values
 * near zero and a RELATIVE one of 1e-9 for values above 1. (An earlier revision
 * of this comment called it purely relative, which it is not.) Both languages
 * use IEEE-754 doubles over the same operation sequence, so agreement should be
 * near-exact either way; a looser bound would hide the algorithmic divergence
 * this test exists to catch. If a case fails, investigate rather than widen.
 */

import { describe, expect, it } from 'vitest'

import fixtures from '../../../supabase/functions/_shared/routeProgress.fixtures.json'
import {
  assess,
  OFF_ROUTE_THRESHOLD_M,
  VERSION,
  type LatLon,
} from '../../../supabase/functions/_shared/routeProgress'

interface Fixture {
  name: string
  input: {
    geometry: number[][]
    position: number[] | null
    plannedDurationMin: number | null
    plannedDistanceKm: number | null
  }
  expected: Record<string, unknown>
}

const cases = fixtures as unknown as Fixture[]
const TOLERANCE = 1e-9

/**
 * An INDEPENDENT great-circle length, written out here rather than imported.
 *
 * The invariant below needs an expected route length that does not come from
 * the code under test. An earlier version fell back to comparing the computed
 * sum against itself when no provider distance was supplied - a tautology that
 * asserted nothing.
 */
function polylineKm(geometry: number[][]): number {
  const R = 6_371_000.0
  const rad = (d: number) => (d * Math.PI) / 180
  let metres = 0
  for (let i = 1; i < geometry.length; i++) {
    const [lat1, lon1] = geometry[i - 1]
    const [lat2, lon2] = geometry[i]
    const a =
      Math.sin(rad(lat2 - lat1) / 2) ** 2 +
      Math.cos(rad(lat1)) * Math.cos(rad(lat2)) * Math.sin(rad(lon2 - lon1) / 2) ** 2
    metres += 2 * R * Math.asin(Math.sqrt(a))
  }
  return metres / 1000
}

function expectNumber(actual: number | null, expected: unknown, field: string, name: string) {
  if (expected === null) {
    expect(actual, `${name}: ${field} should be null`).toBeNull()
    return
  }
  const e = expected as number
  expect(actual, `${name}: ${field} should not be null`).not.toBeNull()
  const a = actual as number
  const scale = Math.max(1, Math.abs(e))
  expect(Math.abs(a - e) / scale, `${name}: ${field} (${a} vs ${e})`).toBeLessThan(TOLERANCE)
}

describe('route progress parity with the Python implementation', () => {
  it('has fixtures to compare against', () => {
    expect(cases.length).toBeGreaterThan(50)
  })

  it.each(cases.map((c) => [c.name, c] as const))('%s', (_name, c) => {
    const got = assess({
      geometry: c.input.geometry.map((p) => [p[0], p[1]] as LatLon),
      position: c.input.position ? ([c.input.position[0], c.input.position[1]] as LatLon) : null,
      plannedDurationMin: c.input.plannedDurationMin,
      plannedDistanceKm: c.input.plannedDistanceKm,
    })

    for (const field of [
      'fraction_complete',
      'travelled_distance_km',
      'remaining_distance_km',
      'off_route_m',
      'remaining_at_planned_pace_min',
      'planned_average_speed_kmph',
    ] as const) {
      expectNumber(got[field], c.expected[field], field, c.name)
    }

    expect(got.on_route, `${c.name}: on_route`).toBe(c.expected.on_route)
    // Order matters: the codes are deduplicated order-preservingly in both.
    expect(got.reason_codes, `${c.name}: reason_codes`).toEqual(c.expected.reason_codes)
    expect(got.version).toBe(c.expected.version)
  })
})

describe('invariants the contract depends on', () => {
  it('never exposes a field that reads as an arrival time', () => {
    // The Python module asserts this too. Publishing the provider's free-flow
    // duration as an ETA would put a timestamp on a manager's screen that a
    // customer is told and nothing in this system stands behind.
    for (const c of cases) {
      for (const key of Object.keys(c.expected)) {
        expect(key.toLowerCase()).not.toContain('eta')
        expect(key.toLowerCase()).not.toContain('arrival')
      }
    }
  })

  it('keeps travelled + remaining equal to an INDEPENDENTLY computed route length', () => {
    for (const c of cases) {
      if (c.expected.travelled_distance_km === null || c.expected.remaining_distance_km === null) continue
      const got = assess({
        geometry: c.input.geometry.map((p) => [p[0], p[1]] as LatLon),
        position: c.input.position ? ([c.input.position[0], c.input.position[1]] as LatLon) : null,
        plannedDurationMin: c.input.plannedDurationMin,
        plannedDistanceKm: c.input.plannedDistanceKm,
      })
      const sum = (got.travelled_distance_km as number) + (got.remaining_distance_km as number)
      // The provider's total when it supplied a usable one; otherwise the
      // polyline length measured by the local haversine above. Never the sum
      // itself.
      const expectedKm =
        c.input.plannedDistanceKm !== null && c.input.plannedDistanceKm > 0
          ? c.input.plannedDistanceKm
          : polylineKm(c.input.geometry)
      expect(
        Math.abs(sum - expectedKm) / Math.max(1, expectedKm),
        `${c.name}: travelled+remaining ${sum} vs ${expectedKm}`,
      ).toBeLessThan(TOLERANCE)
    }
  })

  it('reports the documented off-route threshold', () => {
    expect(OFF_ROUTE_THRESHOLD_M).toBe(200.0)
    expect(VERSION).toBe('route-progress-v1')
  })

  it('returns nulls, never zeroes, when nothing can be computed', () => {
    // A truck with no fix has not arrived.
    const r = assess({ geometry: [[26, 91], [27, 92]], position: null })
    expect(r.fraction_complete).toBeNull()
    expect(r.remaining_distance_km).toBeNull()
    expect(r.on_route).toBeNull()
    expect(r.reason_codes).toEqual(['NO_POSITION_AVAILABLE'])
  })
})
