/**
 * Route progress — a line-for-line port of app/domain/route_progress.py.
 *
 * Deno-compatible and dependency-free so Edge Functions can import it directly.
 *
 * THIS IS A PORT, NOT A REIMPLEMENTATION. Every constant, branch, clamp and
 * ordering decision below mirrors the Python original, because both must agree
 * for as long as both exist. `routeProgress.parity.test.ts` checks this port
 * against fixtures generated by running the Python implementation, so a drift
 * in either direction fails a test rather than showing a driver one number and
 * a manager another.
 *
 * The reasoning behind the algorithm lives in the Python module's docstring and
 * is not duplicated here; what IS repeated is any comment explaining a choice a
 * porter could plausibly "clean up" and thereby break.
 */

export const VERSION = 'route-progress-v1'

const EARTH_RADIUS_M = 6_371_000.0

/**
 * How far off the planned line a truck may be before it is called off-route.
 * A project-defined operational threshold, not a standard.
 */
export const OFF_ROUTE_THRESHOLD_M = 200.0

export const REASON_NO_POSITION = 'NO_POSITION_AVAILABLE'
export const REASON_NO_GEOMETRY = 'ROUTE_HAS_NO_GEOMETRY'
export const REASON_OFF_ROUTE = 'VEHICLE_OFF_PLANNED_ROUTE'
export const REASON_PACE_IS_PLANNED = 'REMAINING_TIME_ASSUMES_PLANNED_PACE'
export const REASON_NO_PACE = 'NO_PLANNED_PACE_AVAILABLE'

/** (lat, lon) — coordinate order matches the Python module and the API. */
export type LatLon = readonly [number, number]

export interface RouteProgress {
  fraction_complete: number | null
  travelled_distance_km: number | null
  remaining_distance_km: number | null
  off_route_m: number | null
  on_route: boolean | null
  remaining_at_planned_pace_min: number | null
  planned_average_speed_kmph: number | null
  reason_codes: string[]
  version: string
}

const radians = (deg: number) => (deg * Math.PI) / 180

/** Great-circle distance in metres. asin(sqrt(a)), matching the Python form. */
export function haversineM(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const p1 = radians(lat1)
  const p2 = radians(lat2)
  const dp = radians(lat2 - lat1)
  const dl = radians(lon2 - lon1)
  const a =
    Math.sin(dp / 2) ** 2 + Math.cos(p1) * Math.cos(p2) * Math.sin(dl / 2) ** 2
  return 2 * EARTH_RADIUS_M * Math.asin(Math.sqrt(a))
}

/**
 * Nearest point on a segment, and how far along it lies.
 *
 * Treated as PLANAR IN DEGREES, with longitude deliberately not rescaled by
 * latitude. That understates east-west distance by ~10% at 26N when choosing
 * WHICH segment is nearest, and it does not matter: the choice is between
 * segments hundreds of metres apart, and the actual distance is then measured
 * with haversine. Do not "fix" this — it would diverge from the Python.
 */
function projectOntoSegment(
  point: LatLon,
  start: LatLon,
  end: LatLon,
): [number, number, number] {
  const [latP, lonP] = point
  const [latA, lonA] = start
  const [latB, lonB] = end

  const dLat = latB - latA
  const dLon = lonB - lonA
  if (dLat === 0.0 && dLon === 0.0) return [latA, lonA, 0.0]

  let t =
    ((latP - latA) * dLat + (lonP - lonA) * dLon) / (dLat * dLat + dLon * dLon)
  t = Math.max(0.0, Math.min(1.0, t))
  return [latA + t * dLat, lonA + t * dLon, t]
}

/** Distance in metres from the start of the line to each vertex. */
function cumulative(geometry: readonly LatLon[]): number[] {
  const out = [0.0]
  for (let i = 1; i < geometry.length; i++) {
    out.push(
      out[out.length - 1] +
        haversineM(geometry[i - 1][0], geometry[i - 1][1], geometry[i][0], geometry[i][1]),
    )
  }
  return out
}

function unavailable(...codes: string[]): RouteProgress {
  return {
    fraction_complete: null,
    travelled_distance_km: null,
    remaining_distance_km: null,
    off_route_m: null,
    on_route: null,
    remaining_at_planned_pace_min: null,
    planned_average_speed_kmph: null,
    reason_codes: codes,
    version: VERSION,
  }
}

export interface AssessInput {
  geometry: readonly LatLon[]
  position: LatLon | null
  plannedDurationMin?: number | null
  plannedDistanceKm?: number | null
}

/**
 * Where along `geometry` the truck at `position` is.
 *
 * Every optional field is null rather than zero when it cannot be computed: a
 * truck with no fix has not arrived.
 */
export function assess({
  geometry,
  position,
  plannedDurationMin = null,
  plannedDistanceKm = null,
}: AssessInput): RouteProgress {
  if (geometry.length < 2) return unavailable(REASON_NO_GEOMETRY)
  if (position === null || position === undefined) return unavailable(REASON_NO_POSITION)

  const cum = cumulative(geometry)
  const totalM = cum[cum.length - 1]
  if (totalM <= 0.0) return unavailable(REASON_NO_GEOMETRY)

  let bestM = Infinity
  let bestAlongM = 0.0
  for (let i = 1; i < geometry.length; i++) {
    const [nearLat, nearLon, t] = projectOntoSegment(position, geometry[i - 1], geometry[i])
    const gap = haversineM(position[0], position[1], nearLat, nearLon)
    // Strict `<` so the FIRST nearest segment wins a tie, exactly as the
    // Python loop does. This is what makes a route that passes itself
    // deterministic rather than order-dependent.
    if (gap < bestM) {
      bestM = gap
      const segmentM = cum[i] - cum[i - 1]
      bestAlongM = cum[i - 1] + t * segmentM
    }
  }

  const travelledM = Math.max(0.0, Math.min(totalM, bestAlongM))
  const fraction = travelledM / totalM

  // Scaled to the provider's total when there is one, so the driver's
  // arithmetic and the manager's screen describe the same road. The FRACTION is
  // untouched: it came from the shape, and scaling a length must not move the
  // truck along it. A zero or negative total is ignored rather than obeyed.
  const routeKm =
    plannedDistanceKm !== null && plannedDistanceKm !== undefined && plannedDistanceKm > 0
      ? plannedDistanceKm
      : totalM / 1000.0
  const travelledKm = fraction * routeKm
  const remainingKm = routeKm - travelledKm
  const onRoute = bestM <= OFF_ROUTE_THRESHOLD_M

  const codes: string[] = []
  // Reported, not corrected. A truck 3 km off still has a projection, and that
  // projection is meaningless — so the figures come back WITH the code saying
  // not to trust them, rather than being suppressed.
  if (!onRoute) codes.push(REASON_OFF_ROUTE)

  let paceKmph: number | null = null
  let remainingMin: number | null = null
  // Mirrors Python's `if planned_duration_min and planned_duration_min > 0`:
  // null, undefined, 0 and negatives all fall to the else branch.
  if (plannedDurationMin !== null && plannedDurationMin !== undefined && plannedDurationMin > 0) {
    // Derived from the SAME distance the driver is shown, so remaining time and
    // remaining distance cannot disagree.
    paceKmph = routeKm / (plannedDurationMin / 60.0)
    if (paceKmph > 0) remainingMin = (remainingKm / paceKmph) * 60.0
    codes.push(REASON_PACE_IS_PLANNED)
  } else {
    // No duration means no pace, and no pace means no remaining time. Not a
    // zero, and not a guess from a default speed: an invented speed produces a
    // number indistinguishable from a measured one.
    codes.push(REASON_NO_PACE)
  }

  return {
    fraction_complete: fraction,
    travelled_distance_km: travelledKm,
    remaining_distance_km: remainingKm,
    off_route_m: bestM,
    on_route: onRoute,
    remaining_at_planned_pace_min: remainingMin,
    planned_average_speed_kmph: paceKmph,
    // Order-preserving dedupe, matching dict.fromkeys.
    reason_codes: [...new Set(codes)],
    version: VERSION,
  }
}
