"""Alembic migration environment.

The database URL comes from application settings, never from alembic.ini, so there
is exactly one source of truth and no credential is written into a tracked file.

Migrations run through a synchronous engine. psycopg3 serves both that and the
async application engine from the same connection URL.
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.core.config import get_settings
from app.db.session import Base

# Importing the models package registers every table on Base.metadata. Without
# it autogenerate sees an empty schema and would propose dropping everything.
import app.models  # noqa: F401  (imported for its registration side effect)

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Inject the real URL from settings, overriding the placeholder in alembic.ini.
#
# effective_migration_url resolves MIGRATION_DATABASE_URL if set, otherwise the
# runtime connection. Both are selected by DATABASE_PROVIDER, so `alembic upgrade`
# always targets the same database the application will serve - it can never
# migrate a local database while the app runs against Supabase.
_settings = get_settings()
# Alembic stores this in a ConfigParser, which treats "%" as interpolation syntax.
# Supabase-generated passwords can contain percent-encoded characters, so an
# unescaped "%" would raise InterpolationSyntaxError on an otherwise valid URL.
config.set_main_option(
    "sqlalchemy.url", _settings.effective_migration_url.replace("%", "%%")
)

target_metadata = Base.metadata


def include_object(object_, name, type_, reflected, compare_to):
    """Keep PostGIS-managed objects out of autogenerated migrations.

    The extension creates spatial_ref_sys and its own views. Without this filter
    autogenerate proposes dropping them, which would break every spatial query.
    """
    if type_ == "table" and name in {"spatial_ref_sys", "geography_columns", "geometry_columns"}:
        return False
    return True


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connect_args: dict[str, object] = {}
    if _settings.requires_ssl and "sslmode=" not in _settings.effective_migration_url:
        connect_args["sslmode"] = "require"

    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
        connect_args=connect_args,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
