"""Alembic migration environment.

The database URL comes from application settings, never from alembic.ini, so there
is exactly one source of truth and no credential is written into a tracked file.

Migrations run through a synchronous engine. psycopg3 serves both that and the
async application engine from the same connection URL.
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.core.config import get_settings
from app.db.schema_ownership import (
    NOT_MIGRATION_OWNED,
    POSTGIS_CORE_RELATIONS,
    make_include_object,
    relations_not_ours,
)
from app.db.session import Base

# Importing the models package registers every table on Base.metadata. Without
# it autogenerate sees an empty schema and would propose dropping everything.
import app.models  # noqa: F401  (imported for its registration side effect)

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Inject the real URL from settings, overriding the placeholder in alembic.ini.
#
# effective_migration_url resolves MIGRATION_DATABASE_URL if set, otherwise the
# runtime connection. Both are selected by DATABASE_PROVIDER, so `alembic upgrade`
# always targets the same database the application will serve - it can never
# migrate a local database while the app runs against Supabase.
_settings = get_settings()
# Alembic stores this in a ConfigParser, which treats "%" as interpolation syntax.
# Supabase-generated passwords can contain percent-encoded characters, so an
# unescaped "%" would raise InterpolationSyntaxError on an otherwise valid URL.
config.set_main_option(
    "sqlalchemy.url", _settings.effective_migration_url.replace("%", "%%")
)

target_metadata = Base.metadata


def _include_object(connection=None):
    """Keep objects this project does not own out of autogenerated migrations.

    Without this filter autogenerate proposes dropping every PostGIS relation
    it can see, which would break every spatial query. Which relations those
    are is asked of the database when there is one to ask - a hardcoded list
    covered `postgis` and missed the tiger geocoder and topology entirely. See
    app/db/schema_ownership for why that matters and how it is decided.

    Offline autogenerate has no connection and falls back to the core PostGIS
    relations, which is what the hardcoded list used to be.

    THE QUERY IS DEFERRED UNTIL THE HOOK IS ACTUALLY CALLED, and that is not an
    optimisation. `context.configure()` runs BEFORE `context.begin_transaction()`,
    so a query issued at configure time opens an implicit transaction on the
    connection; Alembic then finds a transaction already in progress, declines
    to own one, and `run_migrations_online` never commits - every `alembic
    upgrade` applies its DDL and throws it away when the connection closes.
    Asking eagerly here made `alembic downgrade base` leave the database at
    head, silently, and `test_upgrade_downgrade_upgrade_cycle` is what caught
    it. `include_object` is never called during a plain upgrade or downgrade,
    only during autogenerate, so deferring means no query at all on the path
    that must not have one.
    """
    hook = None

    def include_object(object_, name, type_, reflected, compare_to) -> bool:
        nonlocal hook
        if hook is None:
            excluded = (
                POSTGIS_CORE_RELATIONS | NOT_MIGRATION_OWNED
                if connection is None
                else relations_not_ours(connection, target_metadata.tables)
            )
            hook = make_include_object(excluded)
        return hook(object_, name, type_, reflected, compare_to)

    return include_object


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=_include_object(),
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connect_args: dict[str, object] = {}
    if _settings.requires_ssl and "sslmode=" not in _settings.effective_migration_url:
        connect_args["sslmode"] = "require"

    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
        connect_args=connect_args,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=_include_object(connection),
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
