"""The three AI surfaces, over one model.

DRIVER-SCOPED BY CONSTRUCTION

Every route here takes `CurrentDriver` and no id. The trip whose facts reach
the model is resolved from the signed-in driver's token, exactly like the rest
of `api/driver.py`, so there is no parameter that could select whose trip is
described. That is the project's standing rule about IDOR shapes, and it is
what makes "another driver's data" untestable rather than merely refused.

THE FACTS ARE COMPUTED, NOT GENERATED

`_trip_facts` builds a plain-text block from the trip row the deterministic
code already produced. The model restates it. Nothing it writes is stored,
nothing it writes changes a trip, and an unavailable fact stays the word
"unavailable" all the way through - `docs/AI_MODELS.md` forbids rendering a
missing value as a plausible one, and a model is the easiest way to break that.
"""

from datetime import datetime, timezone
from typing import Any, Annotated, Literal

from fastapi import APIRouter, Body, status as http_status
from pydantic import Field

from app.api.deps import CurrentDriver, DbSession
from app.core.errors import APIError
from app.domain import ai_prompts
from app.schemas.common import APIModel, ReadModel
from app.services import driver_trips, gemini, inference

router = APIRouter(prefix="/api/ai", tags=["ai"])


class AiStatusRead(ReadModel):
    available: bool
    provider: str | None
    model: str | None
    #: Why it is unavailable, in words a driver can act on.
    detail: str | None
    #: Language codes the demo is prepared to translate between.
    languages: dict[str, str]
    #: Per-provider health (NOT_CONFIGURED | CONFIGURED | HEALTHY | FAILED |
    #: RATE_LIMITED) with the last error category. Never a key or a URL.
    providers: dict[str, dict[str, Any]] = Field(default_factory=dict)


class AskRequest(APIModel):
    mode: Literal["assistant", "safety", "translate"]
    question: Annotated[str, Field(min_length=1, max_length=1000)]
    #: Bundled, already-reviewed guidance for `safety`. Sent by the client so
    #: the model explains the SAME text the driver is reading, rather than a
    #: server-side copy that may have drifted from the bundle in the app.
    guidance: Annotated[str, Field(default="", max_length=4000)]
    source_language: Annotated[str, Field(default="en", max_length=8)]
    target_language: Annotated[str, Field(default="hi", max_length=8)]
    #: The app's language: the answer must come back in it.
    language: Annotated[str, Field(default="en", max_length=8)]
    #: Facts the deterministic engine on the phone already holds (route
    #: decision, weather line, next stop...). Text only, bounded, no identity
    #: or document numbers - the client builds it from the same answer objects
    #: it renders. Added to the server's own trip facts.
    context: Annotated[str, Field(default="", max_length=2000)]


class AskResponse(ReadModel):
    answer: str
    #: Always true when generated by model, false when from deterministic offline library.
    generated: bool
    model: str | None
    #: When the trip facts behind the answer were read. Separate from the
    #: answer's own time: a fresh sentence about a stale fact is still stale.
    facts_as_of: datetime | None
    severity: str = "INFO"
    source_mode: str = "LIVE_DATA"
    actions: list[str] = Field(default_factory=list)
    disclaimer: str | None = None
    #: GOOGLE_GEMINI | OPENROUTER | OFFLINE_ASSISTANT
    provider: str = "OFFLINE_ASSISTANT"


def _fact(label: str, value: object) -> str:
    """One fact line. `None` becomes the word, never a zero or a blank."""
    return f"- {label}: {'unavailable' if value in (None, '') else value}"


async def _trip_facts(db, driver) -> tuple[str, datetime | None]:
    """The signed-in driver's own trip, as text.

    Returns the word "unavailable" for anything the application does not know,
    and says plainly when there is no trip at all - which is a different answer
    from a trip with no data, and a driver acts differently on each.
    """
    trip = await driver_trips.current_trip(db, driver)
    if trip is None:
        return ("- You have no active trip right now.", None)

    now = datetime.now(timezone.utc)
    lines = [
        _fact("Trip code", trip.trip_code),
        _fact("Status", trip.status.value if trip.status else None),
        _fact("Started at", trip.started_at),
        _fact("Planned ETA", trip.planned_eta),
        _fact("Delay minutes", trip.delay_minutes),
    ]
    return ("\n".join(lines), now)


@router.get("/status", response_model=AiStatusRead, summary="Is a model available")
async def ai_status(driver: CurrentDriver) -> AiStatusRead:
    """Checked live, not cached.

    Checks Gemini Developer API first, then falls back to local inference status.
    """
    gemini_res = await gemini.status()
    if gemini_res.available:
        return AiStatusRead(
            available=True,
            provider=gemini_res.provider,
            model=gemini_res.model,
            detail=gemini_res.detail,
            languages=ai_prompts.DEMO_LANGUAGES,
            providers=gemini.HEALTH,
        )

    local_res = await inference.status()
    if local_res.available:
        return AiStatusRead(
            available=True,
            provider=local_res.provider,
            model=local_res.model,
            detail=local_res.detail,
            languages=ai_prompts.DEMO_LANGUAGES,
        )

    return AiStatusRead(
        available=False,
        provider=gemini_res.provider or local_res.provider,
        model=None,
        detail=gemini_res.detail or local_res.detail,
        languages=ai_prompts.DEMO_LANGUAGES,
        providers=gemini.HEALTH,
    )


@router.post("/ask", response_model=AskResponse, summary="Ask the AI model")
async def ask(
    driver: CurrentDriver,
    db: DbSession,
    payload: Annotated[AskRequest, Body()],
) -> AskResponse:
    """One question, one answer, no history.

    Stateless on purpose. A conversation would have to be stored somewhere, and
    a stored conversation about a driver's trip is a new retention question for
    a demo feature. Each question carries its own facts instead.
    """
    facts_as_of: datetime | None = None

    if payload.mode == "translate":
        system = ai_prompts.TRANSLATE_SYSTEM
        user = ai_prompts.translation_prompt(
            payload.question, payload.source_language, payload.target_language
        )
    elif payload.mode == "safety":
        system = ai_prompts.SAFETY_SYSTEM
        user = ai_prompts.safety_prompt(payload.question, payload.guidance)
    else:
        facts, facts_as_of = await _trip_facts(db, driver)
        if payload.context.strip():
            facts = f"{facts}\n{payload.context.strip()}"
        system = ai_prompts.ASSISTANT_SYSTEM
        user = ai_prompts.assistant_prompt(payload.question, facts)
    system = ai_prompts.in_language(system, payload.language)

    gemini_res = await gemini.generate(
        system=system,
        user=user,
        driver_id=str(driver.id),
        mode=payload.mode,
    )

    if (
        payload.mode == "translate"
        and ai_prompts.TRANSLATION_UNAVAILABLE in gemini_res.answer.upper()
    ):
        raise APIError(
            "The installed model could not translate into that language.",
            code="TRANSLATION_UNAVAILABLE",
            status_code=http_status.HTTP_422_UNPROCESSABLE_ENTITY,
        )

    return AskResponse(
        answer=gemini_res.answer,
        generated=gemini_res.source_mode != "CACHED_DATA",
        model=gemini_res.model,
        facts_as_of=facts_as_of,
        severity=gemini_res.severity,
        source_mode=gemini_res.source_mode,
        actions=gemini_res.actions,
        disclaimer=gemini_res.disclaimer,
        provider=gemini_res.provider,
    )
