"""Generate src/components/northEastStates.ts from geo/RASTA_NER_8_STATES_SoI.svg.

The SVG is the supplied vector of the eight North-Eastern states, derived from the
Survey of India OVSF/1M/7 STATE_BOUNDARY layer. Nothing is redrawn: each state's
own path is kept, simplified with Douglas-Peucker at TOLERANCE viewBox units
(about 0.2 px at the largest size the map is shown) to keep the login bundle
small, rounded to 0.1, and zero-area slivers (rings under 4 points) are dropped.
Label positions are the SVG's own.

    python manager-web/geo/build_ner_map.py
"""
import math
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "RASTA_NER_8_STATES_SoI.svg"
OUT = HERE.parent / "src" / "components" / "northEastStates.ts"
TOLERANCE = 0.35
MARGIN = 20


def dp(points, tol):
    if len(points) < 3:
        return points
    (x1, y1), (x2, y2) = points[0], points[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy)
    best, idx = -1.0, 0
    for i, (x, y) in enumerate(points[1:-1], 1):
        d = abs(dy * x - dx * y + x2 * y1 - y2 * x1) / norm if norm else math.hypot(x - x1, y - y1)
        if d > best:
            best, idx = d, i
    if best <= tol:
        return [points[0], points[-1]]
    return dp(points[: idx + 1], tol)[:-1] + dp(points[idx:], tol)


def ring_d(ring):
    pts = dp(ring, TOLERANCE)
    out = []
    for x, y in pts:
        p = (round(x, 1), round(y, 1))
        if not out or out[-1] != p:
            out.append(p)
    if len(out) < 4:
        return None
    return "M" + "L".join(f"{x:g},{y:g}" for x, y in out) + "Z"


svg = SRC.read_text(encoding="utf-8")
states, xs, ys = [], [], []
for name, d in re.findall(r'data-state="([^"]+)" d="([^"]+)"', svg):
    rings = []
    for part in re.split(r"(?=M )", d.strip()):
        pts = [tuple(map(float, m)) for m in re.findall(r"(-?[\d.]+),(-?[\d.]+)", part)]
        if pts:
            r = ring_d(pts)
            if r:
                rings.append(r)
                xs += [p[0] for p in pts]
                ys += [p[1] for p in pts]
    states.append([name, "".join(rings)])

labels = {}
for x, y, body in re.findall(r'<text class="label" x="([\d.]+)" y="([\d.]+)">(.*?)</text>', svg):
    name = re.sub(r"<[^>]+>", " ", body).split()
    labels[" ".join(name)] = (float(x), float(y))

view = (math.floor(min(xs)) - MARGIN, math.floor(min(ys)) - MARGIN,
        math.ceil(max(xs) - min(xs)) + 2 * MARGIN, math.ceil(max(ys) - min(ys)) + 2 * MARGIN)
lines = [
    "/* Generated by manager-web/geo/build_ner_map.py from geo/RASTA_NER_8_STATES_SoI.svg",
    " * (Survey of India OVSF/1M/7 state boundaries). Do not edit by hand. */",
    "",
    f"export const NER_VIEW = {{ x: {view[0]}, y: {view[1]}, w: {view[2]}, h: {view[3]} }}",
    "",
    "export const NER_STATES: { name: string; d: string; label: [number, number] }[] = [",
]
for name, d in states:
    lx, ly = labels[name]
    lines.append(f"  {{ name: {name!r}, label: [{lx}, {ly}], d: {d!r} }},".replace("'", "'"))
lines.append("]")
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(OUT, OUT.stat().st_size, "bytes;", "view", view)
